### ISSUE TITLE
FOP / DITA Open Toolkit install instructions

### ISSUE THREAD

**Issue by Enigma644** [rototor/jeuclid#13]
I see in comments that in order to use the FOP plugin I need to call:
`JEuclidFopFactoryConfigurator.configure()`
But how do I do that if I'm trying to use the FOP plugin with the DITA Open Toolkit?

OT v3.6.1 has Batik v1.13, so I assume that version should work ok.
I've copied the core and fop jar into with DITA-OT /lib, but I'm getting an `Unknown formatting object` error, presumably because I've not yet enabled the FOP plugin?

Any help would be much appreciated!

**Comment by rototor** [comment]
Sorry, I have no idea about FOP. Please look here https://github.com/rototor/jeuclid/pull/5, maybe that helps. The FOP support existed originally in the project, I removed it but @dubinsky brought it back.

Regarding Batik, you can always use and depend on the latest version. Batik is in pure "serve security fixes" only mode, so there is not really any difference in Batik 1.16 beside some security fixes.

**Comment by Enigma644** [comment]
@dubinsky any insights?

**Comment by dubinsky** [comment]
@Enigma644 
>But how do I do that if I'm trying to use the FOP plugin with the DITA Open Toolkit?

I have no idea what DITA Open Toolkit is, but in order for the JEuclid FOP plugin to be available during a FOP run,
whatever code runs FOP - and obtains an instance of `org.apache.fop.apps.FopFactory` to do so - needs to register the plugin with FOP, for instance, by calling [`JEuclidFopFactoryConfigurator.configure()`](https://github.com/rototor/jeuclid/blob/master/jeuclid-fop/src/main/java/net/sourceforge/jeuclid/fop/plugin/JEuclidFopFactoryConfigurator.java#L6).

Original FOP plugin auto-registered with FOP, but when restoring it, I switched to manual registration in order to be able to experiment with alternative ways of typesetting mathematics with FOP but without JEuclid. Approach with spawning an external Node process running MathJax for each piece of mathematics, even though not very elegant and probably slower than using JEuclid, turned out preferable for me, because of the abysmal quality of the typesetting delivered by the long-abandoned JEuclid compared to the quality delivered by the actively-developed MathJax.

I ended up not having JEuclid on my classpath, so if restoring the self-registration approach of the original FOP plugin works for you better than adding explicit programmatic registration, feel free to restore the `META-INF/services` [files](https://github.com/rototor/jeuclid/commit/439b8528594089df9c65b24d045354e6efdd79c4#diff-a83a43fc7a7b3d43b86ea5c1d042f3cb5ca6c36dca1a3991996160636b446b47) that were removed when FOP plugin was removed and that I did not bring back when I brought the plugin back...
